### ISSUE TITLE
Bitwig does not query the note ports and always assumes an input and an output port

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#10]
Bitwig seems to always assume a plugin has an input and an output note port, and it never tries to query the note port extension. This has the consequence that all CLAP plugins will eat MIDI signals, as Bitwig will not pass notes through plugins that output notes themselves.

**Comment by abique** [comment]
I've done some work, we can try that soon.

**Comment by abique** [comment]
Fix confirmed by @robbert-vdh
