### ISSUE TITLE
Bitwig 4.3 beta 4 can't get proper controls on CLAP plugin parameters

### ISSUE THREAD

**Issue by x-iso** [free-audio/interop-tracker#13]
At least on Windows 10, whenever I load CLAP plugin in Bitwig 4.3 beta 4, the plugin parameter knobs don't seem to work. They could be displaying incorrect value and they don't do anything, while GUI can adjust parameters (if it's present).

**Comment by abique** [comment]
Hi, with which plugin did you have the issue?

**Comment by x-iso** [comment]
So far I have tried SurgeXT and [nih-plugs](https://nightly.link/robbert-vdh/nih-plug/workflows/build/master/nih-plugs-4dd275a-windows)
![image](https://user-images.githubusercontent.com/13594634/172683776-478acb1b-c8a1-4e02-87ba-86d4d5c5269f.png)

![image](https://user-images.githubusercontent.com/13594634/172684290-ac4a17a7-9a7c-4158-a86e-530a20e00c35.png)
as you can see here, knobs on device and GUI are independent of each other, and moving knobs on device can only reset value in Surge to 0 and doesn't move from there. on NIH plugs I don't get any interaction at all.

I don't think this was an issue on 4.3 beta 3 though, only started to act up on beta 4 for me

**Comment by x-iso** [comment]
everything seems to be working fine in 4.3 Beta 5!
