### ISSUE TITLE
UI nitpick: Inconsistent/redundant labeling of plugin types in BWS

### ISSUE THREAD

**Issue by mkruselj** [free-audio/interop-tracker#15]
![image](https://user-images.githubusercontent.com/2393720/173134723-90a12811-9f93-4880-849f-fa98738c0222.png)

Only CLAP get "plug-ins" appended here in Bitwig, VST and VST3 don't. It'd look way cleaner if it just said CLAP and "plug-ins" showed up nowhere.

Ditto in the big browser:

![image](https://user-images.githubusercontent.com/2393720/173134812-0e91587b-f036-4ca8-a68f-50757364072f.png)

It's at least consistent here, but feels unnecessary. We know they're plugins, no? And in case of CLAP, P already does mean "plugin" :)

**Comment by abique** [comment]
This is because you have been using bitwig for a long time and those locations were added at a time where we did not add the "Plug-ins".

If you delete those locations and restart bitwig then they should all have "Plug-ins".

**Comment by mkruselj** [comment]
Hm, ok. I still dislike the redundancy because P in CLAP already means "plugin" 😀
