### ISSUE TITLE
Bitwig does not sum monophonic and polyphonic modulation

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#16]
In Bitwig Studio 4.3 beta 5, applying a monophonic modulator to a parameter and then polyphonically modulating the same parameter completely nullifies the first modulator:

https://user-images.githubusercontent.com/748520/173136034-2bdb62b0-c474-421a-8c38-966604463e6d.mp4

Tested with Surge XT and a couple of other synths.

**Comment by abique** [comment]
Will be fixed with the next release.
