### ISSUE TITLE
Bitwig modulators - per voice indicator sometimes displays too many voices

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#17]
Bitwig 4.3 beta 5
Bitwig modulator set to per-voice mode.

Those cute little balls that show the number of currently active voices in the modulators, they sometimes show too many of them, as it sometimes doesn’t clear them when the voice stops.

Happens rather randomly, haven’t found a reliable pattern to reproduce yet, but only takes a minute of playing to find it.

**Comment by robbert-vdh** [comment]
Yeah this has been happening since the feature was first introduced and Surge implemented it. (so it's not a regression, and presumably not an issue on your plugin's side)

**Comment by abique** [comment]
I think it it fixed for 4.3 beta 10 or 4.3.

**Comment by tas-from-planet-u-he** [comment]
In Bitwig 4.3 beta 10 I found out why there are still too many active voices displayed sometimes. It's connected to playing notes with a velocity value of 1. Submitted a new issue for this: https://github.com/free-audio/interop-tracker/issues/31
