### ISSUE TITLE
Bitwig modulators - switching from global to per-voice keeps the last global mod amount displayed

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#18]
Bitwig 4.3 beta 5

If you switch a modulator from global mode to per-voice mode while a voice is still playing, the current modulation depth is still displayed until you switch back to global modulation.

https://user-images.githubusercontent.com/107404067/173338066-aa4dec12-5d55-426d-8f09-049019608231.mp4

**Comment by abique** [comment]
Should be fixed in Bitwig 4.3 Beta 8.

**Comment by tas-from-planet-u-he** [comment]
Yup, fixed.
