### ISSUE TITLE
Bitwig modulators: per-voice modulation animation

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#19]
Bitwig 4.3 beta 5

Could the per-voice modulation also be animated around the modulated parameter in the device panel?
Currently that only works for global (blue) modulation, but not for per-voice (green) modulation.

**Comment by abique** [comment]
We never do green modulation feedback.
I've fixed the code that takes the average of all voices modulation and then update the modulation feedback.

**Comment by tas-from-planet-u-he** [comment]
That works great, thanks. 👍
