### ISSUE TITLE
Bitwig modulators - per-voice modulator & non-voiced parameters

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#20]
Bitwig 4.3 beta 5

If a per-voice modulator is assigned to a non-polyphonic parameter (e.g. a parameter in the effects section of a u-he plugin), it currently doesn’t modulate it at all. You’d have to switch the modulator to global mode to make it work.
Could it automatically detect that there is a monophonic parameter and send monophonic modulation for this parameter? And at the same time still send per-voice modulation to polyphonic parameters?

**Comment by abique** [comment]
Should be fixed in bitwig 4.3 beta 9

**Comment by tas-from-planet-u-he** [comment]
Yes, it works, yay.
But I noticed something odd, submitted an issue: https://github.com/free-audio/interop-tracker/issues/32
