### ISSUE TITLE
Bitwig's audio engine crashes when using some modulators with the clap-saw-demo

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#23]
When using Bitwig 4.3 beta 6 and this commit of the clap-daw-demo: https://github.com/surge-synthesizer/clap-saw-demo/commit/28ed7138f51be7ca56013308e9eedb9d682b3288 Playing three or more notes at the same time results in a full audio engine crash regardless of plugin hosting mode when the project file linked below. I tested this with the Linux version, in case that ends up making a difference.

[clap-saw-mod-crash.tar.gz](https://github.com/free-audio/interop-tracker/files/8914064/clap-saw-mod-crash.tar.gz)

**Comment by abique** [comment]
Should be fixed with bitwig 4.3 beta 9
