### ISSUE TITLE
bws43b6 paramRequestFlush with processing off doesn't result in call to paramsFlush

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#24]
1. build `clap-saw-demo` at [6414fb1](https://github.com/surge-synthesizer/clap-saw-demo/commit/6414fb1fb1df27eb015938e24937650836e5713d) or later
2. Load it in bitwig
3. open the UI
4. power off the plugin (like the gif below)
5. Drag a slider

at this point the synth will call paramsRequestFlush when you drag. But in the bws43b6 mac engine, rather than getting a call to paramsFlush (which would print to the log and return) I get no call and in the BWS log see

```
PluginDeviceContentsNode request processing
PluginDeviceContentsNode request processing
PluginDeviceContentsNode request processing
PluginDeviceContentsNode request processing
PluginDeviceContentsNode request processing
PluginDeviceContentsNode request processing
```

![Power](https://user-images.githubusercontent.com/13387561/174297349-28604999-0197-4c67-8b07-03b1b17c84e0.gif)

**Comment by abique** [comment]
Request flush can result in either a call to process or a flush_params.
I've done some changes in Bitwig so if I bypass ACE, and turn knobs from ACE gui, then I get the change back in bitwig's device but not the way around yet.

**Comment by baconpaul** [comment]
so right
bws43b8 when you call paramsRequestFlush does a startProcessing / process / stopProcessing

and also prints a message to the log

I guess that's OK? Is there any condition in which BWS calls paramFlush?

**Comment by abique** [comment]
Yes, if the plugin is deactivated, and not about to be destroyed.

**Comment by abique** [comment]
I would not be surprised if paramFlush() never happen for now.
I may use it if the plugin is bypassed though.

**Comment by abique** [comment]
I close this issue as it is not a misbehavior and after looking into it more, it would complicate the code to much to justify the change.
