### ISSUE TITLE
Bitwig can't handle its spicy food

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#25]
Having 🌶 in your plugin features array causes the plugin to not scan. Please fix!

(this is a serious bug report by the way, the actual issue is that Bitwig does not correctly parse some UTF-8 in places where UTF-8 is allowed)

**Comment by tas-from-planet-u-he** [comment]
If emojis are used in the preset description field of u-he .h2p presets, then Bitwig will also crash when loading or modifying such presets.
This happens with the VST version as well, so it's not a problem exclusive to CLAP.

**Comment by abique** [comment]
Should be fixed in Bitwig 4.3 Beta 8.

**Comment by baconpaul** [comment]
🥓 🎹 🧰  here we come
