### ISSUE TITLE
Bitwig browser: favouriting CLAP plugins won't be remembered

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#26]
Bitwig 4.3 beta 6

In Bitwig’s browser, if you star (favourite) a CLAP plugin, this doesn’t get saved.
It will still be starred if you reopen the browser during the same session.
But if you quit and restart Bitwig, the CLAP plugin will no longer be starred.

**Comment by abique** [comment]
Fixed in next Bitwig Studio version (> 4.3 beta 8).

**Comment by tas-from-planet-u-he** [comment]
Yup, fixed. Checked with Bitwig 4.3 beta 10 on Mac M1 Silicon Monterey.
