### ISSUE TITLE
Bitwig: PolyMod over-creates LFOs with note expressions

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#27]
@abique just duping this https://github.com/surge-synthesizer/clap-saw-demo/issues/13 over here since I think it's a bitwig bug. Will update but want an issue in both repos.

Looks like when i play that 2 note thing on mac i end up with poly 2 in my synth but loads of LFOs. On win it apparently crashes.

**Comment by baconpaul** [comment]
OK @abique this is definitely not a clap-saw-demo thing (but there might be an interaction).

when I load the project in attached issue on macOS in bws43b7 even before I press transport, I have 6 or 7 voices going on the LFO. All have note id -1 and pck -1. i don't know what starts them or why.

it used to be the clap saw demo applied modulations to all voices in this case; now it only applies it to playing voices. That may resolve some of the issue but clearly bitwig is doing something really wierd with this project.

**Comment by mobiuscog** [comment]
Just to add it also happens on the latest u-he CLAP plugins in my testing, even though they don't respond to MPE. In fact, you can disable MPE on the device, and the crash still happens - you just need an LFO 'added' as a modulator, not necessarily doing anything.

Removing the note expressions in the example seems to fix the crash as well. It also seems to be related to the 'ending' of the higher note - it crashes just after that - although if I reduce the length of the lower note, at some point it also stops crashing.

**Comment by abique** [comment]
Fixed for 4.3 beta 10 (or 4.3 final).
