### ISSUE TITLE
Reliable crash BWS 43b7 with a note expression plugin in engine

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#29]
First grab https://github.com/baconpaul/MTSToNoteExpression and build it

You don't need MTS-ESP for this crash. It happens in a simple case

Make your gutter MTSToNoteExpression into Poly Grid.

Then just start playing notes quickly (like play fingers up the keyboard over and over)

on a bout note 30 or 40 if you play quickly, blammo, reliable crash.

The crash is in bitwig, not my plug.

<img width="1139" alt="Screen Shot 2022-06-20 at 9 17 42 PM" src="https://user-images.githubusercontent.com/13387561/174696455-cc321d01-4b79-4486-bc63-15bd8b6311d5.png">

and here's a video of it working until it crashes:

https://youtu.be/8UwzEzxZPNY

**Comment by abique** [comment]
Hi, it doesn't crash here.

**Comment by abique** [comment]
I added note latch + arp in front, so it generates thousand of notes very quickly, but it still works.

**Comment by abique** [comment]
![image](https://user-images.githubusercontent.com/31200/174747659-bf84a72f-4f53-465e-9425-791abda4319f.png)
I've been running that for quite some time now, no crash.

**Comment by abique** [comment]
I even ran it with ubsan + asan, no problems.
Maybe something else fixed it in 4.3 beta 8.

**Comment by baconpaul** [comment]
Great. I will test it in 43b8 after we do our livestream. :)

**Comment by abique** [comment]
It isn't out yet, maybe tomorrow.

**Comment by baconpaul** [comment]
yeah I just saw!

If i don't crash in 43b8 then

1. I'll close this and
2. I'll finish that plugin. So people can use MTS-ESP with all the bitwig native devices....

**Comment by abique** [comment]
@baconpaul 4.3b8 is out :-)

**Comment by baconpaul** [comment]
It is indeed resolved in 43b8. Thanks!
