### ISSUE TITLE
Surge sends CLAP_EVENT_PARAM_VALUE back to the host

### ISSUE THREAD

**Issue by abique** [free-audio/interop-tracker#3]
Surge seems to send back to the host CLAP_EVENT_PARAM_VALUE.
This creates a feedback loop with Bitwig's modulation.

**Comment by baconpaul** [comment]
I have fixed this in the latest clap-juce-adapters and have a PR ready to go for when BW 421 is out to build a new nightly. Thanks!

**Comment by abique** [comment]
Fix confirmed.
