### ISSUE TITLE
BWS 43b7 and guiAdjustSize in Surge throw hostMisbheaving

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#30]
This one is a bit tricky to repro - full directions below. It's only tricky cause you need a custom build of surge though

So with Surge XT now I implemented aspect ratio drag, dragging a window in macOS throws a host misbehaving terminate. It's a one pixel error but it shows that bitwig is wrong somewhere.

Here's my log

```
Applying plugin instance state
 *w=1113 *h=762 becomes  *w=1113 *h=762
libc++abi: terminating
 *w=1113 *h=762 becomes  *w=1113 *h=762
guiSetSize with 1113 762
 *w=1113 *h=762 1.f * width / height=1.46063 aspectRatio=1.46042
 *w=1113 *h=762 becomes  *w=1112 *h=762
clap_plugin_gui.set_size() was called with a size which was not adjusted by clap_plugin_gui.adjust_size(): 1113x762 vs 1112x762
```

So obviously I haven't merged this :) But here's how you can do it

```
git clone https://github.com/surge-synthesizer/surge
cd surge
git submodule update --init --recursive
cd libs/clap-juce-extensions
git remote add bp https://github.com/baconpaul/clap-juce-extensions
git fetch bp
git checkout constrainers
cd ../..
cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
cmake --build build --target surge-xt_CLAP
```

then run that clap on macOS, resize the window and almost immediately, blammo

Ideas?

**Comment by abique** [comment]
@baconpaul could it be that your calculation of adjustSize isn't stable?
we could assert that `adjustSize(adjustSize(x, y)) == adjustSize(x, y)`

**Comment by abique** [comment]
I could add that to clap-helpers

**Comment by abique** [comment]
I've added it to clap-helpers

**Comment by baconpaul** [comment]
All good points. But yes I just checked and I'm stable.

With that branch (now updated to latest helpers and also adding a stability check of my own) I see 

```
788x540 becomes 788x539
788x539 becomes 788x539
STABILITY CHECK 788 539 result in 788 539
clap_plugin_gui.set_size() was called with a size which was not adjusted by clap_plugin_gui.adjust_size(): 788x540 vs 788x539
```

with 43b8. That stability check is me checking myself and as you can see

1. you call adjust with 788x540
2. i modify that to 788 x 539
3. my stability check shows that 788x539 roundtrips ok
4. you call set size with 788x540 and i terminate

but there's definitely something funky. if i always only adjust width i have no problem. so i'm not sure i'm not wrong but i'm not not sure either.

**Comment by baconpaul** [comment]
it really might be me. don't spend time on this one quite yet. I'll reopen it if i find out it is you. 

May have a bigger problem though that I can't figure out a stable algorithm for aspect ratio based resize constraints if i dont know the user drag gesture direction

**Comment by abique** [comment]
I double check Bitwig code.

**Comment by abique** [comment]
How is it doing with bitwig 4.3 beta 9?
Did you have a chance to update clap-helpers?

**Comment by baconpaul** [comment]
Yeah clap helpers is at head 

inwill try and look tomorrow before I get away

**Comment by baconpaul** [comment]
The short answer is "yes"

the longer answer is: if I set mode to terminate and maximal i reliably get a core dump when resizing even with the naive approach I hav enow

I think (think) because the drag is happening in sub-pixel size on my retina mac the uint32 rounding is causing instability

I'm not actually sure this can be easily fixed though. I worry that without knowing things like the drag edge and size at start of drag we can't reliably write a resize given just a momentary width height and aspect ratio.

But I think the issue here isn't bitwig. It's that it is impossible to write an aspect ratio constraint which is stable with the information we have. So I think we should close this and start a discussion.
