### ISSUE TITLE
Bitwig & u-he velocity value 1 issues

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#31]
Tested with Bitwig 4.3 beta 10 & u-he Hive revision 13239 on M1 Silicon macOS Monterey 12.4.

Attached an example Bitwig project file:
[Bitwig-u-he-velocity-one-issues.bwproject.zip](https://github.com/free-audio/interop-tracker/files/8984785/Bitwig-u-he-velocity-one-issues.bwproject.zip)

When playing notes with a MIDI velocity value of 1, the MIDI data is reaching the plugin, but the note will not play.
Would expect this with a velocity of 0. But with velocity of 1 it should play.
This happens in the VST3 and CLAP version of u-he plugins, but not with the VST2 version, which plays fine.

MIDI velocity 1 seems to translate to Bitwig velocity settings below 0.40%.
Note will play with 0.40% velocity, but is silent with 0.35% velocity.

I am not sure if this is a Bitwig or a u-he problem, could totally be our fault.
But there is no such problem with the VST3 version when used in Reaper.

There is one more detail, if you use a per-voice modulator and play a note with velocity 1, then the active voice indicator (the little ball in the modulator display) will get stuck, as if the note isn't being freed when released.

You can see the issue when playing the example project, just watch the per-voice modulator.

**Comment by tas-from-planet-u-he** [comment]
The fix added to u-he CLAP plugins in rev. 13241 works. Now notes with a velocity of 1 will play.
Notes with a velocity set to 0.0% in Bitwig will also play.

**Comment by abique** [comment]
I've done some improvement in our velocity conversion as well in Bitwig.
Should be in 4.3.1

**Comment by tas-from-planet-u-he** [comment]
Yes, great. In Bitwig 4.3.1 the VST3 version will also react correctly now, playing notes sent with velocity 1. Super.
