### ISSUE TITLE
Bitwig modulation depth issue with per-voice modulation on non-polyphonic parameters

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#32]
Tested with Bitwig 4.3 beta 10 & u-he Hive revision 13239 on M1 Silicon macOS Monterey 12.4.

Sending a per-voice modulator to a monophonic parameter, such as Hive's distortion amount in the fx section, now works, yay.

But there is something odd going on when playing more than one voice at a time.
The actual modulation depth seems to change rather randomly with each new voice played.
I'd expect the modulation depth to stay the same.

Attached a video to demonstrate. Just listen and watch the modulation amount animation in the Bitwig device panel.

https://user-images.githubusercontent.com/107404067/175774879-f876d8d8-6dc2-46a5-b586-e257dc25fb52.mp4

Also attached an example project. Just click on Hive's distortion amount parameter so you can see the modulation depth in the device panel. Then press play and watch the device panel.
[CLAP modulate mono effect per-voice.bwproject.zip](https://github.com/free-audio/interop-tracker/files/8984793/CLAP.modulate.mono.effect.per-voice.bwproject.zip)

**Comment by abique** [comment]
(deleted)

**Comment by abique** [comment]
Here I average the modulation amount, but this is maybe the problem!

**Comment by abique** [comment]
Fixed in Bitwig > 4.3 Beta 10

**Comment by tas-from-planet-u-he** [comment]
In the Bitwig 4.3 release version, per-voice modulation on a non-polyphonic parameter, such as Hive's FX distortion amount, simply does nothing, no modulation at all.
Switching the modulator to global mode does work.

**Comment by abique** [comment]
Will be fixed in 4.3.1

**Comment by tas-from-planet-u-he** [comment]
Yup, works great with 4.3.1. Thx.
