### ISSUE TITLE
Bitwig modulator not working in global(mono) mode anymore

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#33]
Bitwig 4.3 beta 10.
Tested with Hive and ACE rev. 13239 on M1 Silicon Mac Monterey 12.4.

Assign Bitwig LFO modulator to a parameter, e.g. filter cutoff, and set a modulation depth.
As the LFO is in global(mono) mode by default, no modulation is applied.
Switch it to per-voice mode, and it works.
Switch off per-voice mode and the modulation stops again.

Was working ok in previous Bitwig betas.

**Comment by abique** [comment]
Fixed for next bitwig release, thanks @tas-from-planet-u-he

**Comment by abique** [comment]
Fixed in Bitwig > 4.3 Beta 10

**Comment by tas-from-planet-u-he** [comment]
Working great in Bitwig 4.3 release version.
