### ISSUE TITLE
Bitwig modulators - deactivated modulation target keeps last modulation value

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/interop-tracker#34]
Bitwig 4.3 beta 10.
Tested with Hive and ACE rev. 13239 on M1 Silicon Mac Monterey 12.4.

Assign a modulator, e.g. LFO, to a target, e.g. to filter cutoff.
Switch LFO to per-voice.
Play and hold some notes.
Now use Shift-click to deactivate the modulation for that target in the inspector on the left side.
The filter will keep the last modulation value assigned to each voice.
So each voice now has a different static cutoff value assigned.

Would expect to reset all voices to the actual value of the cutoff knob.

**Comment by abique** [comment]
Fixed in Bitwig > 4.3 Beta 10

**Comment by tas-from-planet-u-he** [comment]
Yep, confirmed fixed in Bitwig 4.3 release. Now resets all voices to the correct value.
