### ISSUE TITLE
Bitwig 4.3.0 does not initialize `process->transport->header`

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#35]
Running on Windows 10 with Bitwig 4.3 demo mode.

In the `clap_plugin_t.process` callback, `clap_process_t.transport->header.type` and `clap_process_t.transport->header.space_id` are both `0`. I was expecting these to be set to `CLAP_EVENT_TRANSPORT` and `CLAP_CORE_EVENT_SPACE_ID` respectively. 

Disclaimer: I don't have a proper debugger setup on Windows at the moment and I discovered this through `printf` debugging. Apologies if I made a mistake and this issue is not actually occurring.

**Comment by abique** [comment]
Good catch!
Fixed for 4.3.1
