### ISSUE TITLE
Display feedback for polyphonic modulation adds up all voices in Bitwig Studio 4.3.1

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#36]
When polyphonically modulating a polyphonically modulatable parameter, the displayed modulation amount shows the modulation sum for all voices:

https://user-images.githubusercontent.com/748520/177760835-8cb37016-ad2e-4232-a909-7bbbcdbc93bf.mp4

The more voices are active here, the more the displayed modulation amount grows.

**Comment by abique** [comment]
Fixed for 4.3.10

**Comment by robbert-vdh** [comment]
Can confirm that this is now fixed in 4.4.1.
