### ISSUE TITLE
BWS 43.1 drum thing doesn't send CLAP_EVENT CHOKE

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#39]
<img width="379" alt="Screen_Shot_2022-07-12_at_11 50 10_AM" src="https://user-images.githubusercontent.com/13387561/179369117-4e69c7c7-4466-42d7-b682-3e7dd342fd51.png">

if I set up two surges in drum thing which send chokes

<img width="604" alt="Screen_Shot_2022-07-12_at_12 32 55_PM" src="https://user-images.githubusercontent.com/13387561/179369129-6c42f074-9ba7-4690-a740-b411f02f65a6.png">

and make surge print when it gets a choke and a note off I only ever get offs, not chokes.

**Comment by abique** [comment]
Fixed for bitwig 4.3.10

**Comment by baconpaul** [comment]
Great
I have one more bug report coming about nore expressions I will write up today

**Comment by abique** [comment]
@baconpaul do you confirm the fix?
If so, please could you close the ticket?

**Comment by baconpaul** [comment]
Oh sorry I will look today

**Comment by baconpaul** [comment]
Yup confirmed in 4.4.5 pre-release i get a CLAP_EVENT_CHOKE coming from drum device. Great!

**Comment by baconpaul** [comment]
And thank you!

**Comment by abique** [comment]
Welcome, and thank you for creating the issue!

**Comment by baconpaul** [comment]
now i need to actually make surge choke notes of course :) 

but i can test that now nicely.
