### ISSUE TITLE
SurgeXT claims to be resize-able but isn't

### ISSUE THREAD

**Issue by abique** [free-audio/interop-tracker#4]
1. surgext says that it is resize-able
2. adjust_size() always returns the current size, maybe override guiAdjustSize() from the clap plugin glue layer?

**Comment by baconpaul** [comment]
Thanks
If I resize from the zoom window (where I initiate) it works but yeah I don’t handle host initiated zooms properly yet. Will address!

**Comment by baconpaul** [comment]
Surge XT at head with 4.3 beta 3 drags to resize no problem. Closing!
