### ISSUE TITLE
Bitwig 4.3 doesn't check CLAP_NOTE_DIALECT

### ISSUE THREAD

**Issue by signaldust** [free-audio/interop-tracker#40]
Bitwig checks note_port->count, but never calls note_port->get (to check what dialects the plugin is willing to support) and simply assumes NOTE_DIALECT_CLAP, sending note-on/note-off messages, so plugins (such as wrapped legacy plugins) that only accept MIDI won't work. Not a huge deal to also accept note-on/note-off, but it still seems like a bug.

@baconpaul confirmed here: https://www.kvraudio.com/forum/viewtopic.php?p=8474546#p8474546

**Comment by abique** [comment]
5.1 will now check the supported note dialect.

if the clap one is support it'll use it, then it'll look for midi mpe and finally midi.

**Comment by baconpaul** [comment]
Fantastic. Curious: will it support MIDI2?

**Comment by abique** [comment]
> Fantastic. Curious: will it support MIDI2?

Possibly in the future.

**Comment by baconpaul** [comment]
Out of curiosity, if you advertise that you support clap but prefer MIDI1 will you ignore the preference? This isn't a problem if you do but i was wondering.

**Comment by abique** [comment]
Bitwig will take what works best for Bitwig.
The clap note dialect give us precise note tuning, which isn't the case with midi or mpe.

**Comment by abique** [comment]
I close, please re-open if this isn't fixed for you.
