### ISSUE TITLE
Bitwig 4.3 doesn't support closing floating GUIs on X11/Linux

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#41]
In the X11/Linux version of my plugin(s) I am using floating windows. Bitwig calls my `clap_plugin_gui_t::is_api_supported` once with `is_floating` false and second with `is_floating` true; I return true to the second call. This behaves as expected, and the GUI window is correctly created with `clap_plugin_gui_t::create` and displayed.

When the close button of the window is clicked (on receiving the `WM_DELETE_WINDOW` event), I call the `clap_host_gui_t->closed` function with `destroyed=true` on the main thread. I expect the host to call `clap_plugin_gui_t::destroy`, but this is not happening with Bitwig.

I am using Bitwig Studio version 4.3.4-1 demo on Arch Linux, from https://aur.archlinux.org/packages/bitwig-studio.

**Comment by abique** [comment]
Hi,
I've just checked the code in Bitwig and indeed I had the inverted check on `was_destroyed`.
Good catch! Thank you.

**Comment by abique** [comment]
Fixed for 4.3.9
