### ISSUE TITLE
Bitwig 4.3 doesn't call show() for non-floating GUIs on X11/Linux

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#42]
For Win32 and X11-floating GUIs, Bitwig calls `show()` after `create()`/`set_parent()`, if I am not mistaken.
However on X11-non-floating GUIs, Bitwig does not call `show()`.
According to the documentation of the GUI extension (https://github.com/free-audio/clap/blob/main/include/clap/ext/gui.h#L28 and https://github.com/free-audio/clap/blob/main/include/clap/ext/gui.h#L115) the host is expected to call `show()`.
Note: This bug does not matter for some plugins, including many of the CLAP example plugins, since they show the window in response to the `create()` or `set_parent()` call.

I am using Bitwig Studio version 4.3.4-1 demo on Arch Linux, from https://aur.archlinux.org/packages/bitwig-studio.

**Comment by abique** [comment]
I'm testing it, and with Hive on X11, I can see that `show()` is even called twice.

**Comment by abique** [comment]
@nakst are you certain that you correctly hooked `show()`?

**Comment by nakst** [comment]
I made this minimal example CLAP plugin, based off the plugin template: https://gist.github.com/nakst/575c89ad2c05a93602c4e245f8c8381b

In particular, here is the relevant part of the plugin's implementation of the GUI extension:
```c
static bool my_plug_gui_create(const clap_plugin_t *_plugin, const char *api, bool is_floating) {
	if (0 == strcmp(api, CLAP_WINDOW_API_X11) && !is_floating) {
		my_plug_t *plugin = (my_plug_t *) _plugin->plugin_data;

		XSetWindowAttributes attributes = {};

		plugin->display = XOpenDisplay(NULL);
		plugin->window = XCreateWindow(plugin->display, DefaultRootWindow(plugin->display), 0, 0, 640, 480, 0, 0, 
				InputOutput, CopyFromParent, CWOverrideRedirect, &attributes);

		uint32_t embedInfoData[2] = { 0 /* version */, 0 /* not mapped */ };
		Atom embedInfoAtom = XInternAtom(plugin->display, "_XEMBED_INFO", 0);
		XChangeProperty(plugin->display, plugin->window, embedInfoAtom, embedInfoAtom, 32, PropModeReplace, (uint8_t *) embedInfoData, 2);

		XSizeHints sizeHints = { .flags = PMinSize | PMaxSize, .min_width = 640, .min_height = 480, .max_width = 640, .max_height = 480 };
		XSetWMNormalHints(plugin->display, plugin->window, &sizeHints);

		XStoreName(plugin->display, plugin->window, s_my_plug_desc.name);

		XSelectInput(plugin->display, plugin->window, SubstructureNotifyMask | ExposureMask | PointerMotionMask 
				| ButtonPressMask | ButtonReleaseMask | KeyPressMask | KeyReleaseMask | StructureNotifyMask
				| EnterWindowMask | LeaveWindowMask | ButtonMotionMask | KeymapStateMask | FocusChangeMask | PropertyChangeMask);

		return true;
	}

	return false;
}

static bool my_plug_gui_show(const clap_plugin_t *_plugin) {
#if IS_GUI_SHOW_REACHED
	// Induce a crash to see whether we reach this point.
	abort();
#endif

	my_plug_t *plugin = (my_plug_t *) _plugin->plugin_data;
	XMapRaised(plugin->display, plugin->window);
	// TODO Start event loop thread.
	return true;
}

static bool my_plug_gui_set_parent(const clap_plugin_t *_plugin, const clap_window_t *window) {
#if IS_GUI_SET_PARENT_REACHED
	// Induce a crash to see whether we reach this point.
	abort();
#endif

	my_plug_t *plugin = (my_plug_t *) _plugin->plugin_data;
	XReparentWindow(plugin->display, plugin->window, (Window) window->x11, 0, 0);
	return true;
}
```

Compiling with

```sh
gcc -o bin/test.clap util/clap_show_test.c -I sdks/clap -l X11 -shared -D IS_GUI_SET_PARENT_REACHED
```

results in the plugin crashing when it is opened, indicating that Bitwig calls into `my_plug_gui_set_parent` as expected.

Compiling with

```sh
gcc -o bin/test.clap util/clap_show_test.c -I sdks/clap -l X11 -shared -D IS_GUI_SHOW_REACHED
```

results in the plugin not crashing when it is opened, indicating that Bitwig has not called into `my_plug_gui_show`.

**Comment by abique** [comment]
You should see in the engine logs: `VST plugin did not create it's window inside the plugin window` which means that you did not re-parent your window.

Bitwig considers it an error.

**Comment by abique** [comment]
I checked your code, and you are missing calls to `XFlush()`, that's why the display server isn't aware of your calls when you return.
