### ISSUE TITLE
Inspector panel MPE toggle does not work as expected

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#43]
Bitwig enables the MPE button by default if a plugin's supported note dialects contains `CLAP_NOTE_DIALECT_MIDI` (that's probably a separate bug, it should only do that when the preferred dialect is `CLAP_NOTE_DIALECT_MIDI_MPE`), but the MPE button doesn't seem to do anything.

I'd expect Bitwig to send CLAP note on, note off, and note expression events when the button is disabled, and MPE-style MIDI events when the button is enabled. This breaks things like MPE pitch bends in plugins that do support MPE but that don't support CLAP note expressions, like JUCE plugins using the clap-juce-extensions or Hive 2.

**Comment by baconpaul** [comment]
yeah i agree; converting to note expressions and note events for plugins which don't say they do clap notes is something it would be lovely to fix!

**Comment by robbert-vdh** [comment]
(this is somewhat related to #40, but the specific issue here is that if a plugin supports both CLAP events and MIDI then Bitwig should just send regular CLAP events when the MPE toggle is disabled, and MPE MIDI when it is enabled)

**Comment by abique** [comment]
This will be gone for clap plugins with bitwig 5.1.
If you want to have midi or midi mpe dialect, then remove the clap dialect from the list of supported dialects.

**Comment by abique** [comment]
I close, please re-open if this isn't fixed for you.
