### ISSUE TITLE
CLAP: Plugin's output Note Expressions in Bitwig cause gliss on note start

### ISSUE THREAD

**Issue by baconpaul** [free-audio/interop-tracker#44]
Hi

It seems if I send a CLAP NOTE_EXPRESSION from a CLAP Note Effect in bitwig at the same time as a note on, then I end up getting a small glissando as if bitwig has somehow delayed the clap note expression. I do not get this if I put note expressions in the piano roll.  Attached is a bitwig file that shows this in BWS 4.3.8. To run it you also need Surge XT (the problem is shown here with both SurgeXT and Polygrid) as well as https://github.com/surge-synthesizer/tuning-note-claps these clap plugins.

[ClapNE Delivery.zip](https://github.com/free-audio/interop-tracker/files/9647831/ClapNE.Delivery.zip)

That example uses the "fixed offset" clap plugin from that set. What fixed offset does at its core is duplicate input events to output events with the exception of `CLAP_NOTE_ON` which does this

```cpp
            case CLAP_EVENT_NOTE_ON:
            {
                auto nevt = reinterpret_cast<const clap_event_note *>(evt);
                auto q = clap_event_note_expression();
                q.header.size = sizeof(clap_event_note_expression);
                q.header.type = (uint16_t)CLAP_EVENT_NOTE_EXPRESSION;
                q.header.time = nevt->header.time;
                q.header.space_id = CLAP_CORE_EVENT_SPACE_ID;
                q.header.flags = 0;
                q.key = nevt->key;
                q.channel = nevt->channel;
                q.port_index = nevt->port_index;
                q.note_id = nevt->note_id;
                q.expression_id = CLAP_NOTE_EXPRESSION_TUNING;

                q.value = neOff;

                // If you comment this line out, bitwig won't crash
                ov->try_push(ov, evt);
                ov->try_push(ov, &(q.header));
            }
            break;
```

As you can see this is adding a tuning note event with a constant offset to every note on. This *should* just transpose the note in the receiving synth. The attached bws file shows this in front of both PolyGrid and Surge XT CLAP.

So what happens is if I take 3 midi notes and add a 24 semitone pitch offset in the piano roll, then everything works.

If instead of that I attach the note expression clap before hand so the clap is generating the expression events I get a small "gliss" at the start of each playback in both surge and polygrid. It is almost (almost) like Bitwig is re-timing all the note expressions from a note event to the start of the subsequent block. 

This is obviously a bummer! It means I can 't write an exciting set of microtonal note effects which use the expressions to retune. 

I think that the fix is inside bitwig to make sure the CLAP note expressions get delivered at the same time as the note like the piano roll does. 

By the way, if we fix this one of the other claps in that set is a full MTS-ESP note expression retuner which means you aren't bound by MPE constraints to retune any note expression aware CLAP in bitwig with MTS-ESP. So this would be super awesome.

**Comment by robbert-vdh** [comment]
Bitwig does the same thing for live played pressure events, so maybe it's related. (try adding a polysynth or something, set the gain to 0, assign pressure from the expressions modulator to the gain knob, and then play a note on a poly pressure capable MIDI controller, the note will always have a small fade in)

EDIT: This now also seems to happen when playing back recorded notes, so maybe it's unrelated. Previously recorded notes played back fine while only live notes had the fade in.

**Comment by baconpaul** [comment]
right so my question is: how do I make a clap plugin that does the same thing as the piano roll.

**Comment by baconpaul** [comment]
if i send the note expression ahead of the note then it seems downstream ignores it also, which i tried.

**Comment by adamski** [comment]
Any updates on this issue? It seems to be essential for any CLAP plugin dealing with tuning or pitch modulation.

**Comment by adamski** [comment]
@abique any updates?

**Comment by mkruselj** [comment]
#51 is possibly the same issue as this one?

**Comment by robbert-vdh** [comment]
#51 is about (polyphonic) modulation, this issue is about note expressions.

**Comment by adamski** [comment]
@abique I'm giving you a nudge following our conversation at Superbooth the other week! ;)

**Comment by abique** [comment]
I haven't had time to look into it yet, sorry about that; I'll try to get that one done for the version 5.0.

**Comment by abique** [comment]
@baconpaul the `Fixed Offset Note Expression` plugin is missing but I could install `tuning-note-claps`.

**Comment by abique** [comment]
It's OK, I can repro.

**Comment by abique** [comment]
I've fixed it! Actually I originally thought that the fix was going to be super dodgy and affect all our note expression smoothing, but I could do something very localized to the plugin.

One limitation of that fix is that it can only track up to 32 notes which starts within one block per plugin instance. The note expressions must be sent exactly on the same time as the note on, if one sample later then it'll be smoothed.

32 could be made bigger, but it is unlikely that we'll tack 16 * 128 at most.

**Comment by abique** [comment]
Should be part of bitwig studio 5.0 beta 10.

**Comment by abique** [comment]
Ah, actually I could clear my started note set after each samples, so the limitation could become 32 notes started per samples.

**Comment by baconpaul** [comment]
that's great. When is 10 ready? I can't wait to try it!

**Comment by baconpaul** [comment]
And as I understand it: My plugin if it gets > 32 note ons on a sample should delay the rest by one sample, and make the note on simultaneous with the tune event.

**Comment by abique** [comment]
If >32 notes on the same sample then 33rd+ notes will have glissando.
But if you start >32 notes at the same time, I guess that it doesn't matter much because it'll be noisy anyway.

**Comment by abique** [comment]
> that's great. When is 10 ready? I can't wait to try it!

We are building it then testing it, so if everything goes well either tonight or tomorrow.

**Comment by baconpaul** [comment]
Seems it is out - got a report from our tuning users today thst the current plugins all work! I’ll spend a bit of time today finishing them up and adding a few edge case corrections. But this is great stuff! Thank you Alex.

**Comment by abique** [comment]
Thank you for catching the issue in first place :handshake:

**Comment by adamski** [comment]
Thank you @abique !! I will check this out as soon as I can and report back. Sounds like the issue is resolved so I can put resources into a CLAP port of our plugin.

**Comment by baconpaul** [comment]
@adamski if you hop onto surge discord you can see the initial write up and results from our CLAP EDN-to-M plugin and MTS ESP client plugin. Which work great!

I think we can definitely close this. It all seems to work for us.
