### ISSUE TITLE
Plugin loads in clap-info and clap-host but not Bitwig (macOS Apple Silicon)

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#45]
I have made a beta version of my free CLAP plugin "Apricot" for Apple Silicon on macOS. It can be downloaded here: https://nakst.itch.io/apricot. It is loading in clap-info and clap-host but not Bitwig 4.3.8, confirmed by baconpaul on Apple Silicon.

The error given is:
```
[2022-09-30 08:52:54.366 float-document-master error] Error loading file /Users/paul/Library/Audio/Plug-Ins/CLAP/Apricot.clap:
        com.bitwig.base.io.FwQ: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not load executable: The bundle couldn’t be loaded.
        at TQy.tUI(SourceFile:40)
```

This is after manually removing the quarantine attribute from the bundle using `xattr`.

We were not able to determine what the plugin is doing wrong that means Bitwig can't load it; the error message given by Bitwig is unfortunately not very helpful.

It has been confirmed to load correctly in Bitwig on macOS 10.15 with an Intel processor (it is a universal binary).

**Comment by abique** [comment]
Did you build a bundle?

**Comment by nakst** [comment]
Yes, it's a bundle.

I have since managed to "fix" the issue by removing the `-mmacosx-version-min` flag from the compiler for the Intel version. I was previously creating a universal binary, combining the Intel version built using `-mmacosx-version-min=10.9`, and the Apple Silicon version built without this flag. I don't know why, but it seems that compiling the Intel version with this flag and putting it in a universal binary prevented Bitwig from loading the Apple Silicon version?

I am completely new to macOS development, so please let me know if you have any further insight as to why this might be happening. But otherwise the issue is mostly resolved.

**Comment by baconpaul** [comment]
set them both to 13 or 14; or set intel to 11 and arm to 14.

**Comment by nakst** [comment]
> set them both to 13 or 14; or set intel to 11 and arm to 14.

Could you link to Apple's documentation where I can learn more about what version combinations I should be using?

**Comment by baconpaul** [comment]
sorry no! I am just using cargo cult knowledge from having shipped some stuff. before 10.14 the arm api is a little grim. 10.9 is super old. We build surge universal at 10.11 and it works fine but that's using cmake so i don't know if it whacks the version for the arm side. My guess is "11 + 15" would work though and no ARM machine runs on an earlier than 15.

**Comment by nakst** [comment]
Ah, I see. I'll close the issue then since it isn't CLAP specific. I'll continue to look into the matter by myself.
