### ISSUE TITLE
CLAP Note Names not appearing in Bitwig 4.3

### ISSUE THREAD

**Issue by jatinchowdhury18** [free-audio/interop-tracker#46]
I've set up a small example plugin in the CLAP JUCE extensions repository, that implements the note name extension: https://github.com/jatinchowdhury18/clap-juce-extensions/blob/note-names/examples/NoteNamesPlugin/NoteNamesPlugin.cpp

When I load the plugin in Bitwg 4.3, the custom note names do not appear in the Bitwig MIDI editor.

**Comment by abique** [comment]
Bitwig currently doesn't support note name invalidation, also I've found that it doesn't deal well with -1 for key/channel.

**Comment by jatinchowdhury18** [comment]
Thanks for looking into this! I've done a bit more hacking, and I think with Bitwig in it's current state I can do all the things I was planning to do with the plugin I'm working on.

That said, if you need a hand testing things around this feature in the future, do let me know! Also feel free to borrow any code from the file I've linked.

**Comment by abique** [comment]
Should be fixed for the next major version.

**Comment by jatinchowdhury18** [comment]
Great thanks! I'll let you know when I get a chance to test :).

**Comment by abique** [comment]
It isn't out yet, you'll have to wait for the next major release

**Comment by abique** [comment]
@jatinchowdhury18 did you get a chance to check? :)

**Comment by jatinchowdhury18** [comment]
Thanks for the reminder! Testing in Bitwig 5.0 Beta 6, and everything seems to be working great!

https://user-images.githubusercontent.com/13724188/235991242-d23cd461-80c1-4f27-94a3-85e85a7869be.mov
