### ISSUE TITLE
Bitwig Studio 4.4.4 sends incorrect values for gain expressions

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#49]
The values Bitwig sends to the plugin for gain expressions are incorrect. Setting a note's gain expression to -12 dB causes Bitwig to emit a volume note expression with value 0.63095737, aka -4 dB. a +12 dB expression gets you 1.5848932, aka +4 dB. The decibel values are always off by a factor 3 as setting -3 dB in Bitwig gets you the equivalent of -1 dB in the note expression and +3 dB in Bitwig gets you +1 in CLAP.

The gain expression values are also off for VST3, but in a completely different way. There -12 dB, 0 dB, and +12 dB result in the plugin receiving note expressions for +2 dB, +6 dB, and +10 dB.

**Comment by abique** [comment]
Hi @robbert-vdh 
Thank you very much for reporting this issue, it is now fixed for bitwig 5.0 beta 7.
