### ISSUE TITLE
Bitwig Studio 4.2.1's audio engine SIGABRTs when a CLAP plugin plays a note that has a pitch expression

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#5]
When this happens, the audio engine reaches a code path that should be unreachable and then crashes, at `src/main/cpp/event/NoteToMidiConverter.cpp:497`. It happens as soon as a note like this gets played:

![afbeelding](https://user-images.githubusercontent.com/748520/160109095-6c8e127f-abfe-4691-af2d-66a1c06aacbe.png)

I tested this on Linux (shouldn't matter) and with the CLAP versions of all of these plugins: https://nightly.link/robbert-vdh/nih-plug/workflows/test/master In case it's relevant, these plugins do not accept `CLAP_EVENT_MIDI_SYSEX` or `CLAP_EVENT_MIDI2` through the event filter, and depending on the plugin they may or may not accept the `CLAP_EVENT_NOTE_*` events (with a corresponding note port if they do support it).

**Comment by abique** [comment]
Ah good catch!
Will be fixed in 4.1.2.

**Comment by abique** [comment]
Actually will be 4.2.3, as 4.2.2 is a hot fix and won't include that fix.
