### ISSUE TITLE
Bitwig shows an error dialog when saving projects containing CLAP plugins with no state

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#50]
This is a pretty rare situation since most plugins will at least have parameters so that's probably why noone's noticed it so far, but if you have a plugin that doesn't implement `CLAP_EXT_STATE` and then try to save the project, you'll get this error:

![image](https://user-images.githubusercontent.com/748520/215787589-3c94f5ff-c24d-43b2-80a9-e0bf008d833c.png)

This happens with Bitwig Studio 4.4.6.

**Comment by abique** [comment]
Sheeeeeeeiiiiiiiiiit.

Do you have a plugin to repro this?

**Comment by robbert-vdh** [comment]
This is the STFT low-pass filter example from NIH-plug as a Linux binary (compiled on Arch, so won't run with older glibc) with the state extension disabled:

[stft.clap.tar.gz](https://github.com/free-audio/interop-tracker/files/10547544/stft.clap.tar.gz)

You can compile this yourself by cloning https://github.com/robbert-vdh/nih-plug, commenting out these two lines: 

https://github.com/robbert-vdh/nih-plug/blob/efff43df21c7f9b4f0a9388c3ec3c05fdf463fb5/src/wrapper/clap/wrapper.rs#L2367-L2368

And then building it by running `cargo xtask bundle stft`.

**Comment by abique** [comment]
Fixed in Bitwig 5.0 Beta 7
