### ISSUE TITLE
Apricot crashes on param mapping indication in Bitwig 5.0 Beta 7

### ISSUE THREAD

**Issue by abique** [free-audio/interop-tracker#52]
You just need to add the plugin and a controller with knobs.

I can't really say which version of the plugin I have, so maybe that helps?
```
md5sum /home/abique/.clap/nakst/Apricot.clap 
af43b698e3cb3e85e3bf834c5e6b5006  /home/abique/.clap/nakst/Apricot.clap
```

The stack trace:
```
2.    /usr/lib/libc.so.6(+0x38f50) [0x7fad2fc71f50]
3.    /home/abique/.clap/nakst/Apricot.clap(+0xd0ecf) [0x7facdaad0ecf]
```

**Comment by nakst** [comment]
Thank you for reporting the issue; this will be fixed in the next update.

**Comment by nakst** [comment]
I have already pushed the fix for my other free plugin, Regency (https://nakst.itch.io/regency).
It would be helpful if you could confirm if this fixes the issue.

**Comment by abique** [comment]
![image](https://user-images.githubusercontent.com/31200/236271323-b265edbc-cd81-4b34-b04a-5d5d16e59798.png)
Fix confirmed!
