### ISSUE TITLE
Bitwig 5 beta 8 sending events not sorted by sample index

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#53]
A project that triggers this (and crashes Apricot) is posted in the #debugging-and-questions channel on the Discord. Happens on both Windows and Linux.

**Comment by abique** [comment]
@nakst could you attach that project here please?

**Comment by nakst** [comment]
Yes, here is the link: https://cdn.discordapp.com/attachments/988476575706136716/1111720620615553184/crashes.bwproject
Playing the project through from the start seems to trigger the crash.

**Comment by abique** [comment]
Here it refuses to load apricot initial plugin state.

**Comment by abique** [comment]
Works with the latest apricot.

**Comment by abique** [comment]
Fixed for bitwig studio 5 beta 10 (did not make it into the beta 9).

**Comment by abique** [comment]
@nakst thanks for the bug report :+1:
