### ISSUE TITLE
Bitwig ignores expressions generated by a CLAP plugin

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#6]
With Bitwig Studio 4.2.3, outputting note expressions from a plugin doesn't seem to work. I created this simple plugin to test it with that essentially passes through all MIDI, but with note numbers/channels/velocities/every else inverted: https://github.com/robbert-vdh/nih-plug/blob/master/plugins/examples/midi_inverter/src/lib.rs

This works fine for notes and MIDI events, but not for the `CLAP_NOTE_EXPRESSION` type events. Removing the inverting behavior and passing everything through as is also strips out the expressions.

The particular plugin is not in the repo's CI builds, but if you want to give it a try then you can install [Rust](https://rustup.rs/) and then clone the repo and build as follows:

```shell
git clone https://github.com/robbert-vdh/nih-plug.git
cd nih-plug
cargo xtask bundle midi_inverter
```

After that you can load `target/bundled/midi_inverter.clap` in Bitwig.

**Comment by baconpaul** [comment]
Oh wow a plugin which outputs note expressions… that could be very sweet
