### ISSUE TITLE
Which CLAP hosts actually support modulation?

### ISSUE THREAD

**Issue by sjoerdvankreel** [free-audio/interop-tracker#60]
Sorry if this has been asked before. I know about https://clapdb.tech/, but that doesn't give me an overview of what DAWs actually implement CLAP_EVENT_PARAM_MOD (either polyphonic or not). For example I am now testing with Reaper 7.11, which has modulators, but they are destructive (i.e. they come in the form of CLAP_EVENT_PARAM_VALUE).

Is it just bitwig I need to worry about? I want to implement (poly) modulation in my plugin, but i'd rather test against a couple of hosts instead of just bitwig.

**Comment by abique** [comment]
Good question.
I'm not aware of another host, but I expect that it'll be available in more hosts over the time.

**Comment by sjoerdvankreel** [comment]
Does the CLAP demo host https://github.com/free-audio/clap-host provide it ? If so, i'll have another go at it. Btw, thanks for the fix https://github.com/free-audio/interop-tracker/issues/54. Will re-test.

**Comment by abique** [comment]
> Does the CLAP demo host https://github.com/free-audio/clap-host provide it ? If so, i'll have another go at it. Btw, thanks for the fix #54. Will re-test.

I think it does, I'm not sure though, long time I haven't used it.

**Comment by sjoerdvankreel** [comment]
Allright. I'm building the reference host right now, but seems like it takes a while. Closing this issue because "bitwig only" for now. Thanks again for the help.

**Comment by Bremmers** [comment]
MultitrackStudio has a "Poly Modulator" MIDI effect which can generate CLAP polyphonic modulation when used in a track with a CLAP instrument.

https://multitrackstudio.com/polymodulator.php

**Comment by sjoerdvankreel** [comment]
Thanks! Nice to see it has free lite version, too.
